### ISSUE TITLE
New nuget version? It seems current nuget version is not up to date and broken

### ISSUE THREAD

**Issue by idchlife** [DmitriyBobrovskiy/CheckReceiptSDK#6]

**Comment by DmitriyBobrovskiy** [comment]
Hi,
Can you provide please more information what is broken?
I just checked and it is working.
I added some tests - you can try to execute it.

**Comment by idchlife** [comment]
@DmitriyBobrovskiy 

this line is not in Nuget package, which makes using library more than once in one session impossible:

https://github.com/DmitriyBobrovskiy/CheckReceiptSDK/blob/master/CheckReceiptSDK/FNS.cs#L175

It fails because headers are trying to be set twice. I checked that github version is working by downloading it and adding package reference to it in .csproj file.

Nuget version is out of date and does not have this fix

**Comment by DmitriyBobrovskiy** [comment]
You are right. I updated the Nuget package.
Thank you.
