### ISSUE TITLE
netstandard

### ISSUE THREAD

**Issue by bessgeor** [DmitriyBobrovskiy/CheckReceiptSDK#8]
Было бы отлично публиковать пакет под netstandard. Чтобы, например, его можно было использовать в Xamarin. Спасибо.

It would be great to publish the package with netstandard TFM. It would make library usable in Xamarin environment. Thanks.

**Comment by DmitriyBobrovskiy** [comment]
На первый взгляд неплохая идея. Не помню, почему не рассматривал это.
В ближайшее время гляну и если не найду противоречий, то залью изменений.

**Comment by DmitriyBobrovskiy** [comment]
Обновленная библиотека с поддержкой .net standard опубликована в [Nuget](https://www.nuget.org/packages/CheckReceiptSDK/) - 1.1.0.
